### ISSUE TITLE
no command

### ISSUE THREAD

**Issue by L2049Q** [arkonique/Back-Projection#1]
Did not find numCompare, distance, etc.

**Comment by arkonique** [comment]
All of these are functions defined in libraries/lib.sh

Please note that this project is not fully functional yet. So any usage problems, algorithm improvement suggestions or contributions are welcome

**Comment by L2049Q** [comment]
@arkonique  Thank you for your reply. Would you like to provide a case? Such as 2011/03/11 M9 Tohoku earthquake.
